server:
  port: 8080
  servlet:
    context-path: /api  # 设置context-path为/api

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: blockchain-certificate

  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blockchain_certificate?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root

  # Jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

# MyBatis-Plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.certificate.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# JWT配置
jwt:
  # JWT加解密使用的密钥
  secret: blockchain-certificate-secret-key
  # JWT的超期限时间(秒) - 7天
  expiration: 604800000
  # JWT在请求头中的名称
  tokenHeader: Authorization
  # JWT前缀
  tokenHead: Bearer
# 跨域配置
cors:
  allowed-origins:
    - http://localhost:3000
    - http://127.0.0.1:3000
    - http://localhost:5173
    - http://127.0.0.1:5173
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true
  max-age: 3600

# Swagger配置
swagger:
  enabled: true
  title: 区块链数字证书管理系统接口文档
  description: 基于区块链的数字证书管理系统
  version: 1.0.0
  contact:
    name: Your Name
    email: your.email@example.com